import Hero from "./_components/Hero";
import Navbar from "./_components/Navbar";
import BestSeller from './_components/BestSeller';
import About from './_components/About';
import Footer from './_components/Footer';
import BottomNav from "./_components/BottomNav";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home | VAM Enterprises",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className="overflow-x-hidden">
      <Navbar/>
      <Hero/>
      <BestSeller/>
      <About/>
      <Footer/>
      <BottomNav/>
    </main>
  );
}
